export const COMPRAS_FETCH_STARTED = 'COMPRAS_FETCH_STARTED';
export const COMPRAS_FETCH_COMPLETED = 'COMPRAS_FETCH_COMPLETED';
export const COMPRAS_FETCH_FAILED = 'COMPRAS_FETCH_FAILED';

export const COMPRA_EXPIRADA_STARTED = 'COMPRA_EXPIRADA_STARTED';
export const COMPRA_EXPIRADA_COMPLETED = 'COMPRA_EXPIRADA_COMPLETED';
export const COMPRA_EXPIRADA_FAILED = 'COMPRA_EXPIRADA_FAILED';

export const COMPRA_ADD_COMPLETED = 'COMPRA_ADD_COMPLETED';
export const COMPRA_ADD_STARTED = 'COMPRA_ADD_STARTED';
export const COMPRA_ADD_FAILED = 'COMPRA_ADD_FAILED';

export const COMPRA_FINALIZADA_STARTED = 'COMPRA_FINALIZADA_STARTED';
export const COMPRA_FINALIZADA_COMPLETED = 'COMPRA_FINALIZADA_COMPLETED';
export const COMPRA_FINALIZADA_FAILED = 'COMPRA_FINALIZADA_FAILED';

export const COMPRA_COMPUTADA_STARTED = 'COMPRA_COMPUTADA_STARTED';
export const COMPRA_COMPUTADA_COMPLETED = 'COMPRA_COMPUTADA_COMPLETED';
export const COMPRA_COMPUTADA_FAILED = 'COMPRA_COMPUTADA_FAILED';
