export const LISTA_ADD_COMPLETED = 'LISTA_ADD_COMPLETED';
export const LISTA_ADD_STARTED = 'LISTA_ADD_STARTED';
export const LISTA_ADD_FAILED = 'LISTA_ADD_FAILED';

export const LISTA_AUMENTAR_STARTED = 'LISTA_AUMENTAR_STARTED';
export const LISTA_AUMENTAR_COMPLETED = 'LISTA_AUMENTAR_COMPLETED';
export const LISTA_AUMENTAR_FAILED = 'LISTA_AUMENTAR_FAILED';

export const LISTA_DISMINUIR_STARTED = 'LISTA_DISMINUIR_STARTED';
export const LISTA_DISMINUIR_COMPLETED = 'LISTA_DISMINUIR_COMPLETED';
export const LISTA_DISMINUIR_FAILED = 'LISTA_DISMINUIR_FAILED';