export const PEDIDOS_CLIENTE_FETCH_STARTED = 'PEDIDOS_CLIENTE_FETCH_STARTED';
export const PEDIDOS_CLIENTE_FETCH_COMPLETED = 'PEDIDOS_CLIENTE_FETCH_COMPLETED';
export const PEDIDOS_CLIENTE_FETCH_FAILED = 'PEDIDOS_CLIENTE_FETCH_FAILED';

export const PEDIDOS_FETCH_STARTED = 'PEDIDOS_FETCH_STARTED';
export const PEDIDOS_FETCH_COMPLETED = 'PEDIDOS_FETCH_COMPLETED';
export const PEDIDOS_FETCH_FAILED = 'PEDIDOS_FETCH_FAILED';

export const PEDIDO_ADD_COMPLETED = 'PEDIDO_ADD_COMPLETED';
export const PEDIDO_ADD_STARTED = 'PEDIDO_ADD_STARTED';
export const PEDIDO_ADD_FAILED = 'PEDIDO_ADD_FAILED';

export const PEDIDO_ENTREGADO_STARTED = 'PEDIDO_ENTREGADO_STARTED';
export const PEDIDO_ENTREGADO_COMPLETED = 'PEDIDO_ENTREGADO_COMPLETED';
export const PEDIDO_ENTREGADO_FAILED = 'PEDIDO_ENTREGADO_FAILED';

export const PEDIDO_CANCELADO_STARTED = 'PEDIDO_CANCELADO_STARTED';
export const PEDIDO_CANCELADO_COMPLETED = 'PEDIDO_CANCELADO_COMPLETED';
export const PEDIDO_CANCELADO_FAILED = 'PEDIDO_CANCELADO_FAILED';
